### ISSUE TITLE
Docker run failed

### ISSUE THREAD

**Issue by narwhrl** [electerm/electerm-web-docker#9]
Docker version : `26.1.2, build 211e74b`
Image version: `docker.io/zxdong262/electerm-web:latest`
System version: `Debian GNU/Linux 12 (bookworm)` (ssh command line env.)
Linux version: `6.8.9-x64v4-xanmod1`
CPU_Arch: `x86_64`

docker run logs:
```
root@narwhrl:~# docker run --init -v /root/electerm-web-data:/home/electerm/data \
  -e "DB_PATH=/home/electerm/data" \
  -e "HOST=0.0.0.0" \
  -e "SERVER=http://127.0.0.1:8082" \
  -p 8082:5577 \
  zxdong262/electerm-web
node:fs:1391
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, mkdir '/home/electerm/data/electerm_session_logs'
    at mkdirSync (node:fs:1391:3)
    at mkdirP (file:///app/electerm-web/src/app/server/session-log.js:12:5)
    at file:///app/electerm-web/src/app/server/session-log.js:21:3
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/electerm/data/electerm_session_logs'
}

Node.js v18.20.
```

**Comment by zxdong262** [comment]
Can you check if current user have permission on folder: /root/electerm-web-data ?

**Comment by narwhrl** [comment]
Thanks! Problem solved with setting the folder 777 permission.
Though it's weird that current user (root) had no permission to mkdir.
Maybe the container use another specific user in docker environment?
